which-ingest: "{!ENV: MERRITT_INGEST !DEFAULT: ingest}"
ingest:
  ingest-info:
    name: "{!SSM: ingest/config/name}"
    identifier: "{!SSM: ingest/config/identifier}"
    target: "{!SSM: ingest/config/target}"
    description: "UC3 ingest micro-service"
    access-uri: "http://{!ENV: HOSTNAME}.cdlib.org:33121"
    ezid: "{!SSM: ingest/ezid-user}:{!SSM: ingest/ezid-password}"
    service-scheme: "Ingest/0.1"
    support-uri: "http://www.cdlib.org/services/uc3/contact.html"
    mail-host: "{!SSM: ingest/config/mail-host !DEFAULT: localhost}"
    mail-contact: "{!SSM: ingest/config/mail-contact !DEFAULT: merritt@cdlib.org}"
    mail-replyto: "{!SSM: ingest/config/mail-replyto !DEFAULT: uc3@ucop.edu}"
    admin: "{!SSM: ingest/config/admin}"
    purl: "http://n2t.net/"
    ingestServicePath: "{!SSM: ingest/config/ingestServicePath !DEFAULT: /dpr2/ingest_home}"
    ingestQueuePath: "{!SSM: ingest/config/ingestQueuePath !DEFAULT: /apps/ingest-stg-shared/ingest_home/queue}"
    # Profiles to S3
    s3config_bucket: "{!SSM: ingest/config/s3-config-bucket !DEFAULT: test.bucket}"
    s3config_prefix: "{!SSM: ingest/config/s3-config-prefix !DEFAULT: uc3/mrt/mrt-ingest-profiles}"

    ingestZfsThreshold: "{!SSM: ingest/config/ingestZfsThreshold !DEFAULT: 80}"
    metadataDisplaySize: "{!SSM: ingest/config/metadataDisplaySize !DEFAULT: 3500}"
    ingestLock: "{!SSM: ingest/zoo/lockName !DEFAULT: /mrt.lock}"
    NumDownloadThreads: "{!SSM: ingest/config/numDownloadThreads !DEFAULT: 4}"

  store-info:
    store.1: "{!SSM: ingest/config/store.1}"
    access.1: "{!SSM: ingest/config/access.1}"
    localID: "{!SSM: ingest/config/localID}"

  queue-info:
    QueueService: "{!SSM: inventory/zoo/queueService}"
    #QueueName: "/ingest"
    #InventoryName: "{!SSM: inventory/zoo/queueName}"
    PollingInterval: "{!SSM: ingest/config/PollingInterval !DEFAULT: 10}"
    NumThreads: "{!SSM: ingest/config/numThreads !DEFAULT: 5}"
    BatchPollingInterval: "{!SSM: ingest/config/BatchPollingInterval !DEFAULT: 15}"
    BatchNumThreads: "{!SSM: ingest/config/BatchNumThreads !DEFAULT: 5}"


  logger-info:
    messageMaximumLevel: "{!SSM: ingest/config/log/messageMaximumLevel !DEFAULT: 5}"
    messageMaximumError: "{!SSM: ingest/config/log/messageMaximumError !DEFAULT: 10}"
    path: "{!SSM: ingest/config/log/path !DEFAULT: logs}"
    name: "ingest"
    qualifier: "yyMMdd"
    trace: 5



ingest-docker:
  ingest-info:
    name: "UC3 Docker Ingest"
    identifier: "ingest"
    target: "http://my-minio-localhost-alias:8086"
    description: "UC3 ingest docker micro-service"
    service-scheme: "Ingest/0.1"
    access-uri: "http://ingest:8080"
    ezid: "example:value"
    support-uri: "http://www.cdlib.org/services/uc3/contact.html"
    # mail-host: "{!SSM: ingest/config/mail-host !DEFAULT: localhost}"
    mail-host: "smtp"
    mail-contact: "merritt@cdlib.org"
    mail-replyto: "uc3@ucop.edu"
    admin: "test@email"
    purl: "http://n2t.net/"
    ingestServicePath: "/tdr/ingest"
    ingestQueuePath: "/tdr/ingest/queue"
    s3endpoint: "{!ENV: S3ENDPOINT}"
    s3accesskey: "{!ENV: S3ACCESSKEY}"
    s3secretkey: "{!ENV: S3SECRETKEY}"
    s3config_bucket: "{!ENV: S3CONFIG_BUCKET !DEFAULT: mrt-config}"
    s3config_prefix: "{!ENV: S3CONFIG_PREFIX !DEFAULT: uc3/mrt/mrt-ingest-profiles}"
    ingestZfsThreshold: "80"
    metadataDisplaySize: "350"
    ingestLock: "/mrt.lock"
    NumDownloadThreads: "2"

  store-info:
    store.1: "http://store:8080/store"
    access.1: "http://store:8080/store"
    localID: "http://inventory:8080/inventory"

  queue-info:
    QueueService: "{!ENV: ZKCONN !DEFAULT: zoo:2181}"
    PollingInterval: "30"
    NumThreads: "3"
    BatchPollingInterval: "15"
    BatchNumThreads: "3"

  logger-info:
    messageMaximumLevel: 5
    messageMaximumError: 10
    path: "logs"
    name: "ingest"
    qualifier: "yyMMdd"
    trace: 5
