which-ingest: "{!ENV: MERRITT_INGEST !DEFAULT: ingest}"
ingest:
  ingest-info:
    name: "{!SSM: ingest/config/name}"
    identifier: "{!SSM: ingest/config/identifier}"
    target: "{!SSM: ingest/config/target}"
    description: "UC3 ingest micro-service"
    access-uri: "http://{!ENV: HOSTNAME}.cdlib.org:33121"
    ezid: "{!SSM: ingest/ezid-user}:{!SSM: ingest/ezid-password}"
    service-scheme: "Ingest/0.1"
    support-uri: "http://www.cdlib.org/services/uc3/contact.html"
    mail-host: "{!SSM: ingest/config/mail-host !DEFAULT: localhost}"
    mail-contact: "{!SSM: ingest/config/mail-contact !DEFAULT: merritt@cdlib.org}"
    mail-replyto: "{!SSM: ingest/config/mail-replyto !DEFAULT: uc3@ucop.edu}"
    admin: "{!SSM: ingest/config/admin}"
    purl: "http://n2t.net/"
    ingestServicePath: "{!SSM: ingest/config/ingestServicePath !DEFAULT: /dpr2/ingest_home}"
    ingestQueuePath: "{!SSM: ingest/config/ingestQueuePath !DEFAULT: /apps/ingest-stg-shared/ingest_home/queue}"
    ingestLock: "{!SSM: ingest/zoo/lockName !DEFAULT: /mrt.lock}"
    NumDownloadThreads: "{!SSM: ingest/config/numDownloadThreads !DEFAULT: 4}"

  store-info:
    store.1: "{!SSM: ingest/config/store.1}"
    access.1: "{!SSM: ingest/config/access.1}"
    localID: "{!SSM: ingest/config/localID}"

  queue-info:
    QueueService: "{!SSM: inventory/zoo/queueService}"
    #QueueName: "/ingest"
    #InventoryName: "{!SSM: inventory/zoo/queueName}"
    PollingInterval: "{!SSM: ingest/config/PollingInterval !DEFAULT: 10}"
    NumThreads: "{!SSM: ingest/config/numThreads !DEFAULT: 5}"
    PollingIntervalHighPriority: "{!SSM: ingest/config/PollingIntervalHighPriority !DEFAULT: 15}"
    NumThreadsHighPriority: "{!SSM: ingest/config/numThreadsHighPriority !DEFAULT: 2}"
    HighPriorityThreshold: "{!SSM: ingest/config/HighPriorityThreshold !DEFAULT: 4}"


  logger-info:
    messageMaximumLevel: "{!SSM: ingest/config/log/messageMaximumLevel !DEFAULT: 5}"
    messageMaximumError: "{!SSM: ingest/config/log/messageMaximumError !DEFAULT: 10}"
    path: "{!SSM: ingest/config/log/path !DEFAULT: logs}"
    name: "ingest"
    qualifier: "yyMMdd"
    trace: 5



ingest-docker:
  ingest-info:
    name: "UC3 Docker Ingest"
    identifier: "ingest"
    target: "http://my-minio-localhost-alias:8086"
    description: "UC3 ingest docker micro-service"
    service-scheme: "Ingest/0.1"
    access-uri: "http://ingest:8080"
    ezid: "example:value"
    support-uri: "http://www.cdlib.org/services/uc3/contact.html"
    # mail-host: "{!SSM: ingest/config/mail-host !DEFAULT: localhost}"
    mail-host: "smtp"
    mail-contact: "merritt@cdlib.org"
    mail-replyto: "uc3@ucop.edu"
    admin: "test@email"
    purl: "http://n2t.net/"
    ingestServicePath: "/tdr/ingest"
    ingestQueuePath: "/tdr/ingest/queue"
    ingestLock: "/mrt.lock"
    NumDownloadThreads: "2"

  store-info:
    store.1: "http://store:8080/store"
    access.1: "http://store:8080/store"
    localID: "http://inventory:8080/inventory"

  queue-info:
    QueueService: "zoo:2181"
    # QueueName: "/ingest"
    # InventoryName: "/mrt.inventory.full"
    BatchPollingInterval: "12"
    BatchNumThreads: "3"
    PollingInterval: "10"
    NumThreads: "3"
    PollingIntervalHighPriority: "15"
    NumThreadsHighPriority: "2"
    HighPriorityThreshold: "5"

  logger-info:
    messageMaximumLevel: 5
    messageMaximumError: 10
    path: "logs"
    name: "ingest"
    qualifier: "yyMMdd"
    trace: 5
